[versions]
agp = "8.2.0"
kotlin = "1.9.20"
compose = "1.5.10"
androidx-activityCompose = "1.8.0"
material = "1.11.0"
odyssey = "1.3.40"
appcompat = "1.6.1"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
android-material = { module = "com.google.android.material:material", version.ref = "material" }
odyssey-core = { module = "io.github.alexgladkov:odyssey-core", version.ref = "odyssey" }
odyssey-compose = { module = "io.github.alexgladkov:odyssey-compose", version.ref = "odyssey" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }


[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose" }
